import Head from 'next/head'
import MyApp from './_app'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Konig Box</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <MyApp/>
      </main>

    </div>
  )
}
